### ISSUE TITLE
Script for regenerating PAC from SVD

### ISSUE THREAD

**Issue by 9names** [Josfemova/eos-s3-rs#2]
Something like https://github.com/rp-rs/rp2040-pac/blob/main/update.sh so that others can make SVD changes and reproduce the PAC.
The script doesn't need to be as complicated as the rp2040 one, but at least having a specific version of svd2rust would allow for repeatable builds.

**Comment by Josfemova** [comment]
I don't know if it would be better to have the SVD in a separate repo tho', right now is for building the PAC, but as QuickLogic does not provide an official one technically it could be useful for people doing Zephyr/Qorc stuff too.
Tying it to the Rust project works for propaganda tho' haha.
Will have the scripts done ASAP. There's a primitive version [here](https://github.com/Josfemova/eos-s3-rs/blob/main/svd/build.sh) but yeah, tying it to a version of svd2rust/svdtools is the correct thing to do

**Comment by Josfemova** [comment]
This should work
<https://github.com/Josfemova/eos-s3-rs/blob/main/generate-pac.sh>
